# Generated by Django 6.0.5 on 2026-05-12 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True)),
                ('aciklama', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Departman',
                'verbose_name_plural': 'Departmanlar',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ad', models.CharField(max_length=50)),
                ('soyad', models.CharField(max_length=50)),
                ('rol', models.CharField(choices=[('ADMIN', 'Admin'), ('IT_UZMANI', 'IT Uzmanı'), ('DEPARTMAN_YONETICISI', 'Departman Yöneticisi'), ('STANDART_KULLANICI', 'Standart Kullanıcı')], default='STANDART_KULLANICI', max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('departman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personeller', to='core.departman')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
                'ordering': ['ad', 'soyad'],
            },
        ),
        migrations.CreateModel(
            name='Donanim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seri_no', models.CharField(db_index=True, max_length=100, unique=True)),
                ('marka', models.CharField(max_length=100)),
                ('model_adi', models.CharField(max_length=100)),
                ('kategori', models.CharField(max_length=100)),
                ('durum', models.CharField(choices=[('DEPODA', 'Depoda'), ('KULLANIMDA', 'Kullanımda'), ('ARIZALI', 'Arızalı'), ('HURDA', 'Hurda')], db_index=True, default='DEPODA', max_length=15)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('zimmetli_kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donanimlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donanım',
                'verbose_name_plural': 'Donanımlar',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='DestekTalebi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('aciklama', models.TextField()),
                ('kategori', models.CharField(choices=[('DONANIM', 'Donanım'), ('YAZILIM', 'Yazılım'), ('AG_ERISIMI', 'Ağ / Erişim'), ('DIGER', 'Diğer')], max_length=15)),
                ('aciliyet', models.CharField(choices=[('DUSUK', 'Düşük'), ('NORMAL', 'Normal'), ('YUKSEK', 'Yüksek'), ('KRITIK', 'Kritik')], default='NORMAL', max_length=10)),
                ('durum', models.CharField(choices=[('YENI', 'Yeni'), ('ISLEMDE', 'İşlemde'), ('BEKLEMEDE', 'Beklemede'), ('COZULDU', 'Çözüldü'), ('KAPATILDI', 'Kapatıldı')], db_index=True, default='YENI', max_length=15)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('atanan_it_uzmani', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atanan_biletler', to=settings.AUTH_USER_MODEL)),
                ('olusturan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acilan_biletler', to=settings.AUTH_USER_MODEL)),
                ('ilgili_donanim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destek_talepleri', to='core.donanim')),
            ],
            options={
                'verbose_name': 'Destek Talebi',
                'verbose_name_plural': 'Destek Talepleri',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='ZimmetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_turu', models.CharField(choices=[('ATAMA', 'Zimmet Atama'), ('IADE', 'Zimmet İade'), ('DURUM_DEGISIKLIGI', 'Durum Değişikliği')], max_length=20)),
                ('aciklama', models.TextField(blank=True, default='')),
                ('islem_tarihi', models.DateTimeField(auto_now_add=True)),
                ('donanim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zimmet_loglari', to='core.donanim')),
                ('eski_kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eski_zimmet_loglari', to=settings.AUTH_USER_MODEL)),
                ('islem_yapan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='yapilan_zimmet_loglari', to=settings.AUTH_USER_MODEL)),
                ('yeni_kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yeni_zimmet_loglari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zimmet Logu',
                'verbose_name_plural': 'Zimmet Logları',
                'ordering': ['-islem_tarihi'],
            },
        ),
    ]
