# Generated by Django 6.0.5 on 2026-05-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donanim',
            name='garanti_bitis_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
