# Generated by Django 6.0.5 on 2026-05-13 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_donanim_garanti_bitis_tarihi'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketYorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField()),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='core.destektalebi')),
                ('yazan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket Yorum',
                'verbose_name_plural': 'Ticket Yorumlar',
                'ordering': ['olusturma_tarihi'],
            },
        ),
    ]
